#' BAf : A package for handling the data from Binder Arrays in facility
#' 
#' @description This package includes class 'BAf' and functions to assist in the
#'   analysis of data generated by Binder Arrays (including suspension bead
#'   arrays) technology in affinity proteomics facility.
#' 
#' @author Mun-Gwan Hong <\email{mun-gwan.hong@scilifelab.se}>
#' @keywords package
#' 
#' @docType package
#' @name BAf-package
#' 
#' @import dplyr
#' @import purrr
NULL



# CONSTANTS

BEADCOUNT_FAILED  = 20
BEADCOUNT_TOO_LOW = 35
